version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./data/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty